### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by hoschi** [BHP-DevHub/react-timeline-9000#128]
It never loads.

**Comment by lilfolr** [comment]
The demo does load, but the bundle is quite large - and hence it takes a while to get going (especially on a slower internet connection).
Will look at optimising/splitting up the bundle

**Comment by vasdee** [comment]
@hoschi what browser were you using at the time?

**Comment by hoschi** [comment]
Chrome Mobile on my Pixel C tablet with wifi.

rob miller <notifications@github.com> schrieb am Sa., 29. Sep. 2018, 10:49:

**Comment by hoschi** [comment]
Tried it on desktop now and it works indeed, but takes really long to load.
