### ISSUE TITLE
Possible to use based on seconds/duration?

### ISSUE THREAD

**Issue by davekiss** [BHP-DevHub/react-timeline-9000#159]
Hey all, this looks really great, nice work.

I'm looking for something that will allow me to add events to a video timeline, so rather than scheduling based on a datetime I'd be scheduling based on a range of seconds ie. 0.000 - 61.235

Is there any way to make that work with your component, or does this only work with dates?

Cheers

**Comment by lilfolr** [comment]
Hi,

The component doesn't support relative datetimes natively, but you might be able to get it to work if you set the start date time something like 1 Jan 2000 and offset your items by that date (bit hacky tho).
You can then use the timebarFormat props to format the top bar to relative time formats

ie `timebarFormat={TIMEBAR_FORMAT}`
```
export const TIMEBAR_FORMAT = {
  majorLabels: {
    minute: {
      short: 'mm', 
      long: 'HH:mm' 
    },
    hour: {
      short: 'HH', 
      long: 'HH:mm'
    },
    day: {
      short: 'DDD', 
      long: ' [Day] DDD' 
    },
    month: {
      short: 'w[+]', 
      long: '[Weeks] w[+]' 
    },
    year: {
        ...
    }
  },
  minorLabels: {
    minute: {
    ...
    }
  }
};
```

Havent tried but should work in theory :)
