### ISSUE TITLE
Items not rendering

### ISSUE THREAD

**Issue by DrEduard** [BHP-DevHub/react-timeline-9000#166]
Hello and thank you for this library.
Testing it with the data generated like in the demo works great. However, when i get my real data, no items show up in the grid. I create the start date like this:
let start = moment(moment("2019-07-24T12:01:06.243").valueOf());
or even let start = moment("2019-07-24T12:01:06.243");
so the start is a Moment object. But then, when i create the end date and push the item to the list, nothing renders.
let end = start.clone().add(30, 'minutes'); //as a test, just to see it rendered, but it will not

Note: if i change the start as in your example to:
let start = moment(data[i].activityList[j].startTime);
      Math.random() * (this.state.endDate.valueOf() - 
      this.state.startDate.valueOf()) +
      this.state.startDate.valueOf()
);
then the items will get rendered. I have no idea why this is happening, tried all sort of ways but did not get to anything that will work with MY data.

Do you have any clue what could be wrong it what i'm doing here?

Thank you guys.

**Comment by lilfolr** [comment]
Hi,
When you're running the demo are you changing the _Date Range_ field to include your new start date?
Note that the date range defaults to `2018-08-31`, so if you pick 2019 as the start date the items wont be visible.

**Comment by DrEduard** [comment]
Hello there again. 
Yeah, that definitely solved my problem... sorry for wasting your time and thank you so much.

**Comment by lilfolr** [comment]
No worries :)
