### ISSUE TITLE
Drag selection does not work if timeline has any horizontal positioning

### ISSUE THREAD

**Issue by marklawlor** [BHP-DevHub/react-timeline-9000#200]
## Description

Timeline selection should work no matter where the timeline is located on the page.

## Steps to reproduce

* Go to demo http://bhp-react-timeline-9k.s3-website-ap-southeast-2.amazonaws.com/
* Open DevTools and add large padding-left to the body element (the higher the better)
* Using your cursor, drag and select only 1 item

Result: Multiple items are selected
Expected result: Only 1 item is selected.

**Comment by lilfolr** [comment]
Confirmed the bug & that #202 fixes it.
Thanks Mark!
