### ISSUE TITLE
selected items off screen breaks timeline

### ISSUE THREAD

**Issue by vasdee** [BHP-DevHub/react-timeline-9000#66]
In the demo, if i select an item(s) then scroll down to effectively push that item off of the screen ( and presumably have it de-rendered by react-virtualised) then initiating another drag event will break the timeline as the selected items prop doesn't match what is shown.

If it is up to the user to keep track of what should be in selected, then the timeline should at least handle these errors gracefully.

**Comment by lilfolr** [comment]
Not sure where we fixed this, but it seems resolved
